import type { LifeTip } from "../types"

const iso = (daysAgo: number) => {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString()
}

export const buildInitialLifeTips = (): LifeTip[] => [
  {
    id: "t-health-1",
    title: "体检与作息备忘",
    summary: "每年一次基础体检；连续熬夜后次日减量运动。",
    body: "## 注意\n- 本文非医疗建议，不适请就医。\n- 体检前一日清淡饮食。",
    category: "HEALTH",
    tags: ["作息", "体检"],
    isPinned: true,
    isFavorite: true,
    updatedAt: iso(2),
  },
  {
    id: "t-cook-1",
    title: "热锅冷油防粘锅",
    summary: "先烧热锅再倒油，下食材更不易粘。",
    body: "铁锅适用；不粘锅勿空烧过久。",
    category: "COOKING",
    tags: ["火候"],
    isPinned: false,
    isFavorite: true,
    updatedAt: iso(5),
  },
  {
    id: "t-chore-1",
    title: "清洁顺序：上到下、干到湿",
    summary: "先收纳再扫地，最后拖地，减少重复劳动。",
    body: "",
    category: "CHORE",
    tags: ["顺序"],
    isPinned: false,
    isFavorite: false,
    updatedAt: iso(1),
  },
  {
    id: "t-drive-1",
    title: "长途前检查轮胎与灯光",
    summary: "胎压、备胎、雨刮水；雨天降速拉大车距。",
    body: "- 证件放固定位置\n- 连续驾驶 2h 休息 15min",
    category: "DRIVING",
    tags: ["长途", "安全"],
    isPinned: true,
    isFavorite: false,
    updatedAt: iso(0),
  },
  {
    id: "t-travel-1",
    title: "出发前证件清单",
    summary: "身份证、护照、机票/车次、充电宝与线。",
    body: "1. 证件\n2. 充电器\n3. 常用药（按需）",
    category: "TRAVEL",
    tags: ["清单"],
    isPinned: false,
    isFavorite: true,
    updatedAt: iso(3),
  },
  {
    id: "t-spend-1",
    title: "大额消费先冷静 24 小时",
    summary: "非急需可隔日再决定，减少冲动下单。",
    body: "",
    category: "SPENDING",
    tags: ["习惯"],
    isPinned: false,
    isFavorite: false,
    updatedAt: iso(10),
  },
  {
    id: "t-dine-1",
    title: "外食先看过敏原与辣度",
    summary: "花生、海鲜等提前问清；聚餐预算心里先有数。",
    body: "",
    category: "DINING",
    tags: ["过敏", "聚餐"],
    isPinned: false,
    isFavorite: false,
    updatedAt: iso(4),
  },
  {
    id: "t-reno-1",
    title: "水电验收拍照留档",
    summary: "打压测试、漏电保护、插座相位可拍照记录。",
    body: "合同变更需书面确认。",
    category: "RENOVATION",
    tags: ["验收"],
    isPinned: false,
    isFavorite: true,
    updatedAt: iso(7),
  },
  {
    id: "t-leisure-1",
    title: "游戏/追剧时间盒",
    summary: "设单次时长上限，避免熬夜影响次日节奏。",
    body: "",
    category: "LEISURE",
    tags: ["时间"],
    isPinned: false,
    isFavorite: false,
    updatedAt: iso(1),
  },
]
